export enum WhichAction {
  COMMIT_TRANSACTION = 'COMMIT_TRANSACTION',
  UPDATE_FOOTER = 'UPDATE_FOOTER',
  CREATE_ACCOUNT = 'CREATE_ACCOUNT',
  UPDATE_ACCOUNTS = 'UPDATE_ACCOUNTS',
  UPDATE_TRANSACTIONS = 'UPDATE_TRANSACTIONS',
  CHANGE_FOOTER = 'CHANGE_FOOTER',
}
